#!/usr/bin/env bash
set -eux

DOCKER=docker
SCRIPT_DIR=$(cd $(dirname $0); pwd)
FIXTURES_DIR=${SCRIPT_DIR}/../fixtures
CONF_DIR=${SCRIPT_DIR}/../configs

# Setup test fixtures

set +x
rm -rf ${FIXTURES_DIR}
mkdir -p ${FIXTURES_DIR}/ethereum/ibc0
mkdir -p ${FIXTURES_DIR}/ethereum/ibc1
set -x

# retrieve the contract information from the container to the local
${DOCKER} cp ethereum-geth0:/root/abis ${FIXTURES_DIR}/ethereum/ibc0/abis
${DOCKER} cp ethereum-geth1:/root/abis ${FIXTURES_DIR}/ethereum/ibc1/abis

${DOCKER} cp ethereum-geth0:/root/addresses ${FIXTURES_DIR}/ethereum/ibc0/addresses
${DOCKER} cp ethereum-geth1:/root/addresses ${FIXTURES_DIR}/ethereum/ibc1/addresses

# assign the contract address to ChainConfig
IBC_HANDLER_ADDRESS_A=`cat ${FIXTURES_DIR}/ethereum/ibc0/addresses/IBCHandler`
IBC_HANDLER_ADDRESS_B=`cat ${FIXTURES_DIR}/ethereum/ibc1/addresses/IBCHandler`
mkdir -p "$CONF_DIR/chains"
jq ".chain.ibc_address |= \"$IBC_HANDLER_ADDRESS_A\"" < "$CONF_DIR/template/ibc-0.template.json" > "$CONF_DIR/chains/ibc-0.json"
jq ".chain.ibc_address |= \"$IBC_HANDLER_ADDRESS_B\"" < "$CONF_DIR/template/ibc-1.template.json" > "$CONF_DIR/chains/ibc-1.json"
