#!/bin/bash

set -eux

source $(cd $(dirname "$0"); pwd)/../../../scripts/util

SCRIPT_DIR=$(cd $(dirname $0); pwd)
PATH_JSON=${1:-path.json}
RLY_BINARY=${SCRIPT_DIR}/../../../../build/yrly
RLY="${RLY_BINARY} --debug"

CHAINID_ONE=ibc0
RLYKEY=testkey
CHAINID_TWO=ibc1
PATH_NAME=ibc01

$RLY tendermint keys show $CHAINID_ONE $RLYKEY
$RLY tendermint keys show $CHAINID_TWO $RLYKEY

# initialize the light client for {{chain_id}}
retry 5 $RLY tendermint light init $CHAINID_ONE -f
retry 5 $RLY tendermint light init $CHAINID_TWO -f

# you should see a balance for the rly key now
# $RLY q bal $CHAINID_ONE
# $RLY q bal $CHAINID_TWO

# add a path between chain0 and chain1
$RLY paths add $CHAINID_ONE $CHAINID_TWO $PATH_NAME --file=./configs/${PATH_JSON}

retry 5 $RLY tx clients $PATH_NAME
$RLY query client $PATH_NAME $CHAINID_ONE 2>/dev/null | jq -Rs 'fromjson'
$RLY query client $PATH_NAME $CHAINID_TWO 2>/dev/null | jq -Rs 'fromjson'

retry 5 $RLY tx connection $PATH_NAME
$RLY query connection $PATH_NAME $CHAINID_ONE 2>/dev/null | jq -Rs 'fromjson'
$RLY query connection $PATH_NAME $CHAINID_TWO 2>/dev/null | jq -Rs 'fromjson'

retry 5 $RLY tx channel $PATH_NAME
$RLY query channel $PATH_NAME $CHAINID_ONE 2>/dev/null | jq -Rs 'fromjson'
$RLY query channel $PATH_NAME $CHAINID_TWO 2>/dev/null | jq -Rs 'fromjson'
