#!/bin/bash

set -eux

source $(cd $(dirname "$0"); pwd)/../../../scripts/util

SCRIPT_DIR=$(cd $(dirname $0); pwd)
RLY_BINARY=${SCRIPT_DIR}/../../../../build/yrly
RLY="${RLY_BINARY} --debug"

CHAINID_ONE=ibc0
CHAINID_TWO=ibc1
RLYKEY=testkey
MOCKAPP_PATH=mockapp-path
ICS20_PATH=ics20-path

if [ "USE_FAKELOST-$USE_FAKELOST" = "USE_FAKELOST-yes" ]; then
  export DEBUG_RELAYER_PRUNE_AFTER_BLOCKS_PROVER_ibc1="10"
  export DEBUG_RELAYER_SHFU_WAIT_ibc0="20"
fi


# add a path between chain0 and chain1
$RLY paths add $CHAINID_ONE $CHAINID_TWO $MOCKAPP_PATH --file=./configs/mockapp-path.json
$RLY paths add $CHAINID_ONE $CHAINID_TWO $ICS20_PATH   --file=./configs/ics20-path.json

retry 5 $RLY tx clients    $MOCKAPP_PATH
retry 5 $RLY tx connection $MOCKAPP_PATH
retry 5 $RLY tx channel    $MOCKAPP_PATH

# copy client-id's from mockapp-path to ics20-path
$RLY paths edit $ICS20_PATH src client-id $($RLY paths list --json | jq --raw-output --arg path_name $MOCKAPP_PATH '.[$path_name].src."client-id"')
$RLY paths edit $ICS20_PATH dst client-id $($RLY paths list --json | jq --raw-output --arg path_name $MOCKAPP_PATH '.[$path_name].dst."client-id"')

# copy connection-id's from mockapp-path to ics20-path
$RLY paths edit $ICS20_PATH src connection-id $($RLY paths list --json | jq --raw-output --arg path_name $MOCKAPP_PATH '.[$path_name].src."connection-id"')
$RLY paths edit $ICS20_PATH dst connection-id $($RLY paths list --json | jq --raw-output --arg path_name $MOCKAPP_PATH '.[$path_name].dst."connection-id"')

retry 5 $RLY tx channel    $ICS20_PATH
