#!/bin/bash

: <<'END_COMMENT'
* relay-interval = 20s
* src-relay-optimize-interval = 30s
* src-relay-optimize-count = 3
* dst-relay-optimize-interval = 30s
* dst-relay-optimize-count = 3
END_COMMENT

set -eux

SCRIPT_DIR=$(cd $(dirname $0); pwd)
source $SCRIPT_DIR/utils
RLY_BIN=${SCRIPT_DIR}/../../../../build/yrly
RLY="${RLY_BIN} --debug"

if [ "USE_FAKELOST-$USE_FAKELOST" = "USE_FAKELOST-yes" ]; then
    export DEBUG_RELAYER_PRUNE_AFTER_BLOCKS_CHAIN_ibc1="10"
    export DEBUG_RELAYER_PRUNE_AFTER_BLOCKS_PROVER_ibc1="10"
    export DEBUG_RELAYER_SHFU_WAIT_ibc0="20"
fi

PATH_NAME=mockapp-path
TM_ADDRESS0=$(${RLY} tendermint keys show ibc0 testkey)

expectUnrelayedCount $PATH_NAME "unrelayed-packets" "src" 0
expectUnrelayedCount $PATH_NAME "unrelayed-packets" "dst" 0
expectUnrelayedCount $PATH_NAME "unrelayed-acknowledgements" "src" 0
expectUnrelayedCount $PATH_NAME "unrelayed-acknowledgements" "dst" 0

${RLY} service start $PATH_NAME --relay-interval 20s --src-relay-optimize-interval 30s --src-relay-optimize-count 3 --dst-relay-optimize-interval 30s --dst-relay-optimize-count 3 &
RLY_PID=$!

sendPacketOnEth $PATH_NAME
waitUnrelayedCount $PATH_NAME "unrelayed-packets" "dst" 1 300

docker exec tendermint-chain0-mock sh -c "simd --home /root/data/ibc0 tx --keyring-backend=test --from ${TM_ADDRESS0} --chain-id ibc0 mockapp send mockapp channel-0 'mock packet data' --yes"
waitUnrelayedCount $PATH_NAME "unrelayed-packets" "src" 1 30

date; echo "Server has started. Both chains already have a message to relay which will be ready after optimize-interval (30s)."

echo "Waiting dst->src packets are relayed. Note that src chain(tendermint) has fast confirmation time"
waitUnrelayedCount $PATH_NAME "unrelayed-packets" "dst" 0 300
echo "Waiting src->dst packets are relayed"
waitUnrelayedCount $PATH_NAME "unrelayed-packets" "src" 0 300

echo "Waiting dst->src ack is relayed. Note that the time of src->dst->src relay and dst->src->dst relay takes nearly same time"
waitUnrelayedCount $PATH_NAME "unrelayed-acknowledgements" "dst" 0 300
echo "Waiting src->dst ack is relayed"
waitUnrelayedCount $PATH_NAME "unrelayed-acknowledgements" "src" 0 300

echo "$0 Finished"

kill $RLY_PID
