FROM ethereum/solc:0.6.4-alpine

RUN apk add --d --no-cache ca-certificates npm nodejs bash alpine-sdk expect jq

RUN git clone https://github.com/binance-chain/bsc-genesis-contract.git -b v1.1.9 /root/genesis \
    && cd /root/genesis && npm ci

COPY scripts/contracts/SystemReward.template /root/genesis/contracts/SystemReward.template
COPY scripts/contracts/BSCValidatorSet.template /root/genesis/contracts/BSCValidatorSet.template
COPY scripts/generate-validator.js /root/genesis/generate-validator.js
COPY scripts/genesis-template.template /root/genesis/genesis-template.template
COPY scripts/init_holders.template /root/genesis/init_holders.template

COPY --from=bsc-rpc:latest /usr/local/bin/geth /usr/local/bin/geth

ENTRYPOINT [ "/bin/bash" ]
